MvcApplication1/Controllers/Emailv2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;

namespace MvcApplication1.Controllers
{
    public class Emailv2Controller : Controller
    {
        //
        // GET: /Emailv2/

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SendMail(Correo correo)
        {
            try
            {
                return View("Enviado", correo);
            }
            catch
            {
                return View();
            }
            

        }
     


    }
}

MvcApplication1/Views/Emailv2/Enviado.cshtml
@model MvcApplication1.Models.Correo

<h1 class="message-success"> Correo enviado satisfactoriamente</h1>
<ul>
    <li><strong>el nombre es </strong>@Html.DisplayFor(m=>m.nombre)</li>
    <li><strong>el apellido es </strong>@Html.DisplayFor(m=>m.apellidos)</li>
    <li><strong>el email es </strong>@Html.DisplayFor(m=>m.email)</li>
    <li><strong>el mensaje es</strong>@Html.DisplayFor(m=>m.mensaje)</li>
</ul>

MvcApplication1/Views/Emailv2/Index.cshtml
@model MvcApplication1.Models.Correo

@using (Html.BeginForm("SendMail","Emailv2" ))
{
    Html.AntiForgeryToken();
<fieldset>
    <legend>correo</legend>
  <div class="editor-label">
      @Html.LabelFor(m=>m.nombre)

  </div>
    <div class="editor-field">
        @Html.TextBoxFor(m=>m.nombre)
    </div>
    <div class="editor-label">
        @Html.LabelFor(m=>m.apellidos)
         </div>
    <div class="editor-field">
        @Html.TextBoxFor(m=>m.apellidos)
    </div>
    <div class="editor-label">
        @Html.LabelFor(m=>m.email)
    </div>
    <div class="editor-field">
        @Html.TextBoxFor(m=>m.email)
    </div>
    <div class="editor-label">
        @Html.LabelFor(m=>m.mensaje)

    </div>
    <div class="editor-field">
        @Html.TextAreaFor(m=>m.mensaje)
    </div>
    <input type="submit" value="Enviar" />
</fieldset>
        
}