MvcApplication1/Controllers/Emailv3Controller.cs
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication1.Models;
using MvcApplication1.Dal;

namespace MvcApplication1.Controllers
{
    public class Emailv3Controller : Controller
    {
        //
        // GET: /Emailv3/
        BasedatosContext contexto = new BasedatosContext();

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Sendmail(CorreoValidacion CorreoValidacion)
        {
            if (!ModelState.IsValid)

                return View("Index");
            try
            {
                contexto.Mensajes.Add(CorreoValidacion);
                contexto.SaveChanges();
                return View("Enviado", CorreoValidacion);
            }
            catch
            {
                return View();
            }

        }
        public ActionResult Details(int id)
        {
            try
            {
                var mensaje = contexto.Mensajes.Where(m => m.ID == id).FirstOrDefault();
                if (mensaje == null)
                {
                    return View();
                }
                else
                {
                    return View("Detalles", mensaje);
                }
            }
            catch
            {
                return View();
            }



        }
       
        public ActionResult Edit(int id)
        {
            try
            {
                var mensaje = contexto.Mensajes.Where(m => m.ID == id).FirstOrDefault();
                if (mensaje == null)
                {
                    return View();
                }
                else
                {
                    return View("Editar", mensaje);
                    
                    
                }

            }
            catch
            {
                return View();
            }
        }
       
        public ActionResult GuardarCambios(CorreoValidacion Correo)
        {
            if (!ModelState.IsValid)
                return View("Index");
                
            try
            {
                
                
                
                    contexto.Entry(Correo).State = EntityState.Modified;
                    return View("List", contexto.Mensajes);
                
            }
            catch
            {
                return View();
            }




        }




        public ActionResult List()
        {
            return View(contexto.Mensajes);
        }
        public ActionResult Delete(int id)
        {
           
            try
            {
                var mensaje = contexto.Mensajes.Where(m => m.ID == id).FirstOrDefault();
                               
                return View("Borrado", mensaje);
                

                 

              
                


            }
            catch
            {
                return View();
            }
        }
        
        public ActionResult Borrar(int id)
        {
           
            try
            {
                var correo = contexto.Mensajes.Find(id);
                contexto.Mensajes.Remove(correo);
                contexto.SaveChanges();
                return View("List", contexto.Mensajes);
            }
            catch
            {
                return View();
            }

        }
        
    
        
        public ActionResult CambiarLenguaje(string Lang)
        {
            var cultura = new System.Globalization.CultureInfo(Lang);
            System.Threading.Thread.CurrentThread.CurrentCulture = cultura;
            System.Threading.Thread.CurrentThread.CurrentUICulture = cultura;
            return View("Index");
        }
     

    }

}

MvcApplication1/Views/Emailv3/Borrado.cshtml
@model MvcApplication1.Models.CorreoValidacion


@{
    ViewBag.Title = "Borrado";
}

<h2>Borrado</h2>

<h3>¿Esta seguro de que quiere borrar el registro?</h3>
<fieldset>
    <legend>CorreoValidacion</legend>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model =>model.nombre )
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.apellido)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.apellido)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.mensaje)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.mensaje)
    </div>
</fieldset>
    <p>
        @Html.ActionLink("Delete", "Borrar", new { id = Model.ID })
        
    </p>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/Views/Emailv3/Detalles.cshtml
@model MvcApplication1.Models.CorreoValidacion

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<fieldset>
    <legend>CorreoValidacion</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.nombre)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.apellido)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.apellido)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.mensaje)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.mensaje)
    </div>
</fieldset>
<div>
    @Html.ActionLink("Volver", "List")
</div>

MvcApplication1/Views/Emailv3/Editar.cshtml
@model MvcApplication1.Models.CorreoValidacion

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm("GuardarCambios","Emailv3")) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>CorreoValidacion</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.nombre)
            @Html.ValidationMessageFor(model => model.nombre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.apellido)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.apellido)
            @Html.ValidationMessageFor(model => model.apellido)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.email)
            @Html.ValidationMessageFor(model => model.email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.mensaje)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.mensaje)
            @Html.ValidationMessageFor(model => model.mensaje)
        </div>

        <p>
            <input type="submit" value="Guardar Cambios" />
        </p>
    </fieldset>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication1/Views/Emailv3/Enviado.cshtml
@model MvcApplication1.Models.CorreoValidacion


<h2 class="message-success"> Correctamente Enviado</h2>
<p>sus datos son</p>
<ul>
    <li><strong>Su nombre es </strong>@Html.DisplayFor(m=>m.nombre)</li>
    <li><strong>Su apellido es </strong>@Html.DisplayFor(m=>m.apellido)</li>
    <li><strong>Su email es </strong>@Html.DisplayFor(m=>m.email)</li>
    <li><strong>Su mensaje es</strong>@Html.DisplayFor(m=>m.mensaje)</li>
</ul>

MvcApplication1/Views/Emailv3/Index.cshtml
@model MvcApplication1.Models.CorreoValidacion
@Literales.Literales.Saludo
@using (Html.BeginForm("SendMail","Emailv3"))
{
    @Html.ActionLink("Español","CambiarLenguaje",new {lang="es"})
@Html.ActionLink("Inglés", "CambiarLenguaje", new { lang = "en" })

    <div class="editor-label">
        @Html.LabelFor(m=>m.nombre)
    </div>
    <div class="editor-text">
        @Html.TextBoxFor(m=>m.nombre)
        @Html.ValidationMessageFor(m=>m.nombre)
    </div>
    <div class="editor-label">
        @Html.LabelFor(m=>m.apellido)

    </div>
    <div class="editor-text">
        @Html.TextBoxFor(m=>m.apellido)
    </div>
    <div class="editor-label">
        @Html.LabelFor(m=>m.email)
    </div>
    <div class="editor-text">
        @Html.TextBoxFor(m=>m.email)
        @Html.ValidationMessageFor(m=>m.email)
        
    </div>
    <div class="editor-label">
        @Html.LabelFor(m=>m.mensaje)
    </div>
    <div class="editor-text">
        @Html.TextAreaFor(m=>m.mensaje)
        @Html.ValidationMessageFor(m=>m.mensaje)
    </div>
    <input type="submit" value="Enviar" />
   
}

@section Scripts {
    @Scripts.Render("~/Bundles/jqueryval");
}

MvcApplication1/Views/Emailv3/List.cshtml
@model IEnumerable<MvcApplication1.Models.CorreoValidacion>

@{
    ViewBag.Title = "List";
}
<p>
    ejemplo de archivo de recursos viendo en que lenguaje está el navegador
</p>



<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.apellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.mensaje)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.apellido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.mensaje)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>